### ISSUE TITLE
Update README, I mean, really.

### ISSUE THREAD

**Issue by haesbaert** [haesbaert/mdnsd#15]

**Comment by rjc** [comment]
Hi,

Is it style or format that you'd like updated or the actual content - as in, the text is no longer accurate or outright wrong? If the former, then let me know what you have in mind and I'll be able to reformat it.

Regards,

rjc

**Comment by haesbaert** [comment]
I think both.

I'd like to have it in markdown, and all that stuff about avahi and bonjour should go.
If you want to work on the format/content you're more than welcome, but I intend to do this at some point.
