### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by jbeich** [haesbaert/mdnsd#16]
From GCC 7.0:
```c
control.c: In function 'control_group_add':
control.c:340:13: warning: variable 'pg' set but not used [-Wunused-but-set-variable]
  struct pg *pg;
             ^~
packet.c: In function 'pkt_parse_rr':
packet.c:962:55: warning: variable 'pl' set but not used [-Wunused-but-set-variable]
  u_int16_t us, rdlen = 0, tmplen, i, code, plen, erc, pl;
                                                       ^~
packet.c:962:50: warning: variable 'erc' set but not used [-Wunused-but-set-variable]
  u_int16_t us, rdlen = 0, tmplen, i, code, plen, erc, pl;
                                                  ^~~
mdns.c: In function 'pge_kill':
mdns.c:959:13: warning: variable 'pg' set but not used [-Wunused-but-set-variable]
  struct pg *pg;
             ^~
mdnsd.c: In function 'fetchhinfo':
mdnsd.c:210:39: warning: '%s' directive output may be truncated writing up to 255 bytes into a region of size between 0 and 255 [-Wformat-truncation=]
  snprintf(hi->os, sizeof(hi->os), "%s %s", utsname.sysname,
                                       ^~
      utsname.release);
      ~~~~~~~                           
mdnsd.c:210:2: note: 'snprintf' output between 2 and 512 bytes into a destination of size 256
  snprintf(hi->os, sizeof(hi->os), "%s %s", utsname.sysname,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      utsname.release);
      ~~~~~~~~~~~~~~~~
```
From scan-build 4.0:
```c
mdnsl.c:347:4: warning: Value stored to 'r' is never read
                        r = mdns_handle_lookup(m, &rr, ev);
                        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mdnsl.c:356:4: warning: Value stored to 'r' is never read
                        r = mdns_handle_browse(m, &rr, ev);
                        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mdnsl.c:365:4: warning: Value stored to 'r' is never read
                        r = mdns_handle_resolve(m, &ms, ev);
                        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mdnsl.c:383:4: warning: Value stored to 'r' is never read
                        r = mdns_handle_group(m, groupname, ev);
                        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mdnsl.c:544:2: warning: Value stored to 'p' is never read
        p = start = namecp;
        ^   ~~~~~~~~~~~~~~
control.c:359:2: warning: Value stored to 'pg' is never read
        pg = pg_get(1, msg, c);
        ^    ~~~~~~~~~~~~~~~~~
packet.c:559:4: warning: Value stored to 'n' is never read
                        n    = 0;
                        ^      ~
packet.c:1167:7: warning: Use of memory after it is freed
                if (qst->flags & QST_FLAG_UNIRESP) {
                    ^~~~~~~~~~
packet.c:1296:3: warning: Value stored to 'len' is never read
                len -= INT16SZ;
                ^      ~~~~~~~
packet.c:1361:3: warning: Value stored to 'len' is never read
                len  -= oslen;
                ^       ~~~~~
packet.c:1375:3: warning: Value stored to 'len' is never read
                len  -= rdlen;
                ^       ~~~~~
packet.c:1386:3: warning: Value stored to 'len' is never read
                len  -= rdlen;
                ^       ~~~~~
packet.c:1411:3: warning: Value stored to 'len' is never read
                len   -= n;
                ^        ~
packet.c:1452:2: warning: Value stored to 'len' is never read
        len  -= n;
        ^       ~
mdns.c:485:3: warning: Use of memory after it is freed
                question_remove(rrs);
                ^~~~~~~~~~~~~~~~~~~~
mdns.c:961:2: warning: Value stored to 'pg' is never read
        pg = pge->pg;
        ^    ~~~~~~~
mdns.c:1129:3: warning: Use of memory after it is freed
                pge_kill(pge);
                ^~~~~~~~~~~~~
```

**Comment by haesbaert** [comment]
From GCC 7.0:

control.c: In function 'control_group_add':
control.c:340:13: warning: variable 'pg' set but not used [-Wunused-but-set-variable]
  struct pg *pg;
             ^~

ok

packet.c: In function 'pkt_parse_rr':
packet.c:962:55: warning: variable 'pl' set but not used [-Wunused-but-set-variable]
  u_int16_t us, rdlen = 0, tmplen, i, code, plen, erc, pl;
                                                       ^~
packet.c:962:50: warning: variable 'erc' set but not used [-Wunused-but-set-variable]
  u_int16_t us, rdlen = 0, tmplen, i, code, plen, erc, pl;
                                                  ^~~

wont fix, might be usable in the future.

mdns.c: In function 'pge_kill':
mdns.c:959:13: warning: variable 'pg' set but not used [-Wunused-but-set-variable]
  struct pg *pg;
             ^~

ok

mdnsd.c: In function 'fetchhinfo':
mdnsd.c:210:39: warning: '%s' directive output may be truncated writing up to 255 bytes into a region of size between 0 and 255 [-Wformat-truncation=]
  snprintf(hi->os, sizeof(hi->os), "%s %s", utsname.sysname,
                                       ^~
      utsname.release);

truncation here is normal, nothing to do.

      ~~~~~~~                           
mdnsd.c:210:2: note: 'snprintf' output between 2 and 512 bytes into a destination of size 256
  snprintf(hi->os, sizeof(hi->os), "%s %s", utsname.sysname,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      utsname.release);
      ~~~~~~~~~~~~~~~~
From scan-build 4.0:

mdnsl.c:347:4: warning: Value stored to 'r' is never read
                        r = mdns_handle_lookup(m, &rr, ev);
                        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mdnsl.c:356:4: warning: Value stored to 'r' is never read
                        r = mdns_handle_browse(m, &rr, ev);
                        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mdnsl.c:365:4: warning: Value stored to 'r' is never read
                        r = mdns_handle_resolve(m, &ms, ev);
                        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mdnsl.c:383:4: warning: Value stored to 'r' is never read
                        r = mdns_handle_group(m, groupname, ev);
                        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

should probably print error here ^

mdnsl.c:544:2: warning: Value stored to 'p' is never read
        p = start = namecp;
        ^   ~~~~~~~~~~~~~~

ok

control.c:359:2: warning: Value stored to 'pg' is never read
        pg = pg_get(1, msg, c);
        ^    ~~~~~~~~~~~~~~~~~

ok

packet.c:559:4: warning: Value stored to 'n' is never read
                        n    = 0;
                        ^      ~

wont change

packet.c:1167:7: warning: Use of memory after it is freed
                if (qst->flags & QST_FLAG_UNIRESP) {
                    ^~~~~~~~~~

false positive ^

packet.c:1296:3: warning: Value stored to 'len' is never read
                len -= INT16SZ;
                ^      ~~~~~~~

wont fix

packet.c:1361:3: warning: Value stored to 'len' is never read
                len  -= oslen;
                ^       ~~~~~
packet.c:1375:3: warning: Value stored to 'len' is never read
                len  -= rdlen;
                ^       ~~~~~
packet.c:1386:3: warning: Value stored to 'len' is never read
                len  -= rdlen;
                ^       ~~~~~
packet.c:1411:3: warning: Value stored to 'len' is never read
                len   -= n;
                ^        ~
packet.c:1452:2: warning: Value stored to 'len' is never read
        len  -= n;
        ^       ~

^^ wont fix, these are safe keepers, if code is added later that depends on len, everyone is happy.

mdns.c:485:3: warning: Use of memory after it is freed
                question_remove(rrs);
                ^~~~~~~~~~~~~~~~~~~~

^^ false positive

mdns.c:961:2: warning: Value stored to 'pg' is never read
        pg = pge->pg;
        ^    ~~~~~~~

ok


mdns.c:1129:3: warning: Use of memory after it is freed
                pge_kill(pge);
                ^~~~~~~~~~~~~

false positive

**Comment by haesbaert** [comment]
I'm closing this, the only thing to consider is the printing on error on mdnsl.c, this cannot be done as that will be a library. When it actually becomes a library, we will have to express that in another way.

Thanks for this, keep them coming :D.
