### ISSUE TITLE
log severity level too high for normal cache_process messages

### ISSUE THREAD

**Issue by nbriggs** [haesbaert/mdnsd#20]
In mdns.c, it seems that the "goodbye" and "refresh" messages should not be logged using log_warnx() which produces LOG_CRIT level messages.  Since these are really an expected part of normal operations they should probably be logged with log_info() or log_debug().

**Comment by haesbaert** [comment]
You're right, I'll fix it for next release.

Thanks for noticing it.

**Comment by nbriggs** [comment]
Thanks.   I was reading the code and considering fixing a few things and putting in a pull request, but when I'm running *BSD it's always FreeBSD so it's a bit awkward to deal with the OpenBSD differences.

-- Nick Briggs

**Comment by haesbaert** [comment]
There is a port for freebsd btw.
Are you using this in any projects ?

**Comment by nbriggs** [comment]
Yeah, I fetched it from the FreeBSD port.  Projects, no, I'm just using it on a few FreeBSD boxes at home because it makes it easy to access them by name from my Macs.  I had a vague idea of adding AAAA records.  The other thing that would interesting to investigate, though perhaps you already know the answer to this, is whether the *BSD nsswitch mechanisms are designed for easy extensibility -- e.g., will they load a shared library whose name is based on the mechanism specified in the /etc/nsswitch.conf and then expect it to implement standard lookups (kind of like PAM modules).  I guess I'd go looking at the libc usage of nsdispatch.


-- Nick

**Comment by nbriggs** [comment]
... the answer on the nsswitch mechanism is... no.  There are only hard-wired sources implemented.

**Comment by nbriggs** [comment]
This is the patch I'd be interested in seeing as part of the next version:

diff --git a/mdnsd/mdns.c b/mdnsd/mdns.c
index 2a9a4f1..23779f7 100644
--- a/mdnsd/mdns.c
+++ b/mdnsd/mdns.c
@@ -176,5 +176,5 @@ cache_process(struct rr *rr)
                                /* A goodbye RR */
                                if (rr->ttl == 0) {
-                                       log_warnx("cache_process: goodbye %s",
+                                       log_info("cache_process: goodbye %s",
                                            rrs_str(&rr->rrs));
                                        cache_delete(rr_aux);
@@ -182,5 +182,5 @@ cache_process(struct rr *rr)
                                }
                                /* Cache refresh */
-                               log_warnx("cache_process: refresh %s",
+                               log_info("cache_process: refresh %s",
                                    rrs_str(&rr->rrs));
                                rr_aux->ttl = rr->ttl;

**Comment by haesbaert** [comment]
Fixed, thanks.
