### ISSUE TITLE
Permit port 0 in a service publication

### ISSUE THREAD

**Issue by nxg** [haesbaert/mdnsd#26]
Some services should, it seems, be served at the dummy port 0, but this is forbidden by `mdnsctl`.

I _think_ that the `._device-info._tcp` service is supposed to be served at port 0 (Macs, for example, advertise this service as a way of broadcasting information about the host).  Unfortunately, I can't find chapter and verse which states this.  However the following observations might be relevant:

  * [This list post](https://lists.apple.com/archives/bonjour-dev/2013/Oct/msg00000.html) discusses `_device-info._tcp`, but without mentioning specifically the port number.
  * The [dns-sd spec](http://files.dns-sd.org/draft-cheshire-dnsext-dns-sd.txt) (p.27) mentions ‘ a placeholder SRV record (priority=0, weight=0, port=0, target host = host name of device)’; this is in a slightly different context, but does seem to indicate that a notional port 0 is a possibility (you'll be more familiar with the spec than I am).
  * Various ‘Avahi & Linux’ blog posts talk about the configuration stanza to get this service served at port 0.  Of course, this type of post tends to have a strong air of voodoo about it, so might not be taken fully seriously.
  * Finally, the OS X `dns-sd` manpage mentions, under its `-R` documentation on ‘register a service’, that the port must be in the range 0 to 65535.

Port 0 is forbidden by `mdnsctl` because of the call:

    res.port = strtonum(word, 1, UINT16_MAX, &errstr);

at line 309 of `parser.c`.  Perhaps explicit

    res.port = strtonum(word, 0, 65535, &errstr);

would be better.

**Comment by haesbaert** [comment]
Thank you, fixed !
