### ISSUE TITLE
OpenBSD libc integration

### ISSUE THREAD

**Issue by xguerin** [haesbaert/mdnsd#28]
Hey there,

You mention in one of your goals libc integration. What is the status of this? I couldn't find any reference to that in OBSD manpages.

Thanks,

**Comment by haesbaert** [comment]
Sorry for the delay.

I sent a diff in 2011: https://marc.info/?l=openbsd-tech&m=130016213004182&w=2

But theo didn't like because blablabalbalbala.
kristapz worked in some code that update hosts, you can see here: pr #14
